apiVersion: v2
name: posey-mcp
description: A Helm chart for Posey MCP Service
type: application
version: 0.1.0
appVersion: "latest"

keywords:
  - posey
  - mcp
  - core

maintainers:
  - name: Posey Labs
    email: dev@posey.ai

dependencies:
  - name: common-helpers
    repository: "file://../../../library/common-helpers" 
    version: "0.1.1"