apiVersion: v1
kind: Service
metadata:
  name: posey-mcp
  namespace: posey
  labels:
    app: posey-mcp
spec:
  selector:
    app: posey-mcp
  ports:
  - port: 5050
    targetPort: 5050
  type: LoadBalancer