apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared/k8s
  - agents/k8s
  - auth/k8s
  - cron/k8s
  - mcp/k8s
  - supertokens/k8s
  - voyager/k8s
  # Reference data services
  - ../data/postgres/k8s
  - ../data/couchbase/k8s 