apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: posey
  namespace: argocd
spec:
  description: Posey AI Platform Project
  
  # Project sources: repositories that can be used for applications in this project
  sourceRepos:
  - '*'  # Allow all repositories. You might want to restrict this to your specific repository
  
  # Destination clusters and namespaces allowed for applications in this project
  destinations:
  - namespace: posey
    server: https://kubernetes.default.svc
  - namespace: posey-staging
    server: https://kubernetes.default.svc
  
  # Allowed Kubernetes resource kinds
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  
  # Allow all namespaced resources 
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  # Role bindings for project access
  roles:
  - name: admin
    description: Full admin privileges for the project
    policies:
    - p, proj:posey:admin, applications, *, posey/*, allow
    groups:
    - posey-admins
  
  # Project orphaned resources monitoring
  orphanedResources:
    warn: true 