apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cron-data-pvc
  namespace: posey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cron-logs-pvc
  namespace: posey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 