# Global values for the Posey monitoring stack
global:
  namespace: monitoring

# OpenTelemetry Collector configuration
otelCollector:
  enabled: true
  image:
    repository: grafana/alloy
    tag: latest
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
      resource:
        attributes:
          - key: service.namespace
            value: "posey"
            action: upsert
    exporters:
      prometheus:
      loki:
      otlp:
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [loki]

# Prometheus configuration
prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 8Gi
  extraScrapeConfigs: |
    - job_name: 'otel-collector'
      scrape_interval: 10s
      static_configs:
        - targets: ['posey-otel-collector:8888']
    - job_name: 'node-services'
      scrape_interval: 10s
      static_configs:
        - targets: ['host.docker.internal:9464']  # Default Node.js exporter port

# Loki configuration
loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
  config:
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks

# Tempo configuration
tempo:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
  server:
    httpListenPort: 3200
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

# Grafana configuration
grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    size: 2Gi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://posey-prometheus-server.monitoring.svc.cluster.local
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://posey-loki.monitoring.svc.cluster.local:3100
          access: proxy
        - name: Tempo
          type: tempo
          url: http://posey-tempo.monitoring.svc.cluster.local:3100
          access: proxy
          uid: tempo
          jsonData:
            httpMethod: GET
            serviceMap:
              datasourceUid: 'prometheus'
            lokiSearch:
              datasourceUid: 'loki'
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: posey-dashboards 