apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-ingress.yaml
- couchbase-ingress.yaml
- vector-db-ingress.yaml
- posey-agents-ingress.yaml
- posey-auth-ingress.yaml
- posey-cron-ingress.yaml
- posey-mcp-ingress.yaml
- posey-supertokens-ingress.yaml
- posey-voyager-ingress.yaml
- configmap.yaml
- tcp-services-configmap.yaml

namespace: posey

# Patches to override namespace for specific ingresses
patches:
- path: argocd-namespace-patch.yaml
  target:
    kind: Ingress
    name: argocd-server-ingress 