apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  # Forward external port 3333 to postgres service on port 3333
  "3333": "posey/postgres:3333"
  # Forward Couchbase ports
  "8091": "posey/couchbase:8091"
  "8092": "posey/couchbase:8092"
  "8093": "posey/couchbase:8093"
  "8094": "posey/couchbase:8094"
  "11210": "posey/couchbase:11210"
  # Forward Qdrant ports
  "6334": "posey/qdrant:6334" 