enableGlobalCache: false

httpTimeout: 300000

logFilters:
  - code: YN0013
    level: discard

networkConcurrency: 1

nmMode: hardlinks-local

nodeLinker: pnp

npmScopes:
  posey.ai:
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
