nodeLinker: node-modules
enableGlobalCache: false
nmMode: hardlinks-local

logFilters:
  - code: YN0013
    level: discard

npmScopes:
  posey.ai:
    npmRegistryServer: "https://registry.npmjs.org"

# Add timeout settings
httpTimeout: 300000
networkConcurrency: 1
