apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-ingress.yaml
- postgres-ingress.yaml
- couchbase-ingress.yaml
- vector-db-ingress.yaml
- agents-ingress.yaml
- auth-ingress.yaml
- cron-ingress.yaml
- mcp-ingress.yaml
- supertokens-ingress.yaml
- voyager-ingress.yaml

namespace: posey

# Patches to override namespace for specific ingresses
patches:
- path: overlays/argocd-namespace-patch.yaml
  target:
    kind: Ingress
    name: argocd-server-ingress 