apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cron-service
  namespace: argocd
  # Add finalizer to ensure related resources are deleted upon application deletion
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Or your specific Argo CD project

  source:
    # Path to the Helm chart within the Git repository
    path: k8s/charts/services/core/cron 
    # URL of the Git repository where the Kubernetes manifests are stored
    repoURL: 'https://github.com/your-org/your-repo.git' # <-- IMPORTANT: Replace with your actual repo URL
    targetRevision: HEAD # Or a specific branch/tag/commit
    helm:
      # Reference values from the Git repository
      valueFiles:
        - values.yaml
      # Optional: Override specific values here if needed for the environment
      # values: |
      #   replicaCount: 2
      #   image:
      #     tag: stable

  destination:
    # Target Kubernetes cluster URL
    server: 'https://kubernetes.default.svc' 
    # Target namespace where the application will be deployed
    namespace: posey-services # Or the appropriate namespace for core services

  # Sync policy
  syncPolicy:
    automated:
      # Automatically prune resources that are not defined in Git
      prune: true 
      # Automatically sync changes detected in Git
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true # Automatically create the namespace if it doesn't exist
      - PruneLast=true # Ensures pruning happens last in the sync operation
      # ApplyOutOfSyncOnly=true # Optional: Only apply changes if the app is OutOfSync
      # ServerSideApply=true # Optional: Use server-side apply for potentially smoother updates 