apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: posey-cron
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: server-side-diff=true
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: posey-cron
    app.kubernetes.io/part-of: posey
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: posey

  source:
    path: k8s/charts/services/core/cron
    repoURL: 'https://github.com/poseylabs/posey'
    targetRevision: main
    helm:
      valueFiles:
        - ../../../base-values.yaml
        - values.yaml
      parameters:
        - name: image.tag
          value: "latest"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: posey

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true