apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voyager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }} # This will be filled by the root app
    targetRevision: HEAD
    path: k8s/charts/services/core/voyager
    helm:
      valueFiles:
        - values.yaml
        # Optionally add environment-specific value overrides
        # - environments/values-production.yaml
      # Pass parameters from the root application or define defaults
      parameters:
        - name: "image.tag"
          value: "latest" # Default tag, can be overridden by CI/CD pipeline
        - name: "image.repository"
          value: "posey/voyager" # Ensure this matches your registry
        # Add other parameters you want to control via ArgoCD UI/CLI
        # - name: "replicaCount"
        #   value: "2"

  destination:
    server: https://kubernetes.default.svc
    namespace: posey # Deploying into the 'posey' namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 