apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: host-patches.yaml

commonAnnotations:
  nginx.ingress.kubernetes.io/ssl-redirect: "false"

patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: postgres-ingress
    namespace: posey
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: postgres.local 