apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resources that should be applied together
resources:
  - qdrant-pvc.yaml
  - qdrant-statefulset.yaml
  - qdrant-service.yaml

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/name: qdrant
  app.kubernetes.io/part-of: posey
  app.kubernetes.io/managed-by: kustomize
  tier: database 