apiVersion: v1
kind: Service
metadata:
  name: posey-qdrant
  namespace: default
  labels:
    app: posey-qdrant
    tier: database
spec:
  # Selector matches the pods created by the StatefulSet
  selector:
    app: posey-qdrant
  # Port mapping
  ports:
  - port: 1111          # The port referenced in ConfigMap
    targetPort: 6333    # The HTTP port Qdrant listens on
    name: http
  - port: 6334          # GRPC port
    targetPort: 6334    # The GRPC port Qdrant listens on
    name: grpc
  # ClusterIP makes the service only accessible within the cluster
  type: ClusterIP 