apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  namespace: default
  labels:
    app: posey-qdrant
    tier: database
spec:
  # ReadWriteOnce means the volume can be mounted as read-write by a single node
  accessModes:
    - ReadWriteOnce
  # Request 20Gi of storage for the vector database
  resources:
    requests:
      storage: 20Gi
  # Digital Ocean's storage class for block storage
  storageClassName: do-block-storage 