apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: posey-appset-base 
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/poseylabs/posey.git
      revision: HEAD
      directories:
      - path: k8s/charts/placeholder/* 

  template:
    metadata:
      name: posey-{{path.basename}}
      labels:
        app: posey-{{path.basename}}
        argocd.argoproj.io/applicationset: posey-appset-placeholder # Patched by overlay
        category: placeholder # Patched by overlay
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: posey

      source:
        repoURL: https://github.com/poseylabs/posey.git
        targetRevision: HEAD
        chart: "{{path}}"
        helm:
          parameters:
          - name: global.image.registry
            value: docker.io/poseylabs
          - name: global.image.pullPolicy
            value: Always
          - name: global.replicaCount
            value: "1" # Needs to be a string for Helm parameters
          - name: global.service.type
            value: ClusterIP
          - name: global.serviceAccount.create
            value: "false" # Also needs to be a string
          - name: global.resources.requests.memory
            value: "512Mi"
          - name: global.resources.requests.cpu
            value: "250m"
          - name: global.resources.limits.memory
            value: "1Gi"
          - name: global.resources.limits.cpu
            value: "500m"
          valueFiles:
            - /k8s/charts/base-values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: posey

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m 