apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agents-data-pvc
  namespace: posey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agents-models-pvc
  namespace: posey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 