apiVersion: apps/v1
kind: Deployment
metadata:
  name: posey-agents
  namespace: posey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posey-agents
  template:
    metadata:
      labels:
        app: posey-agents
    spec:
      containers:
      - name: posey-agents
        image: registry.digitalocean.com/posey/posey-agents:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.5"
        envFrom:
        - configMapRef:
            name: posey-shared-env
        - secretRef:
            name: posey-secrets
        env:
        - name: COUCHBASE_ADMIN_URL
          value: http://couchbase:8091
        volumeMounts:
        - name: agents-data
          mountPath: /app/data
        - name: agents-models
          mountPath: /app/models
        livenessProbe:
          httpGet:
            path: /health
            port: 5555
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5555
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: agents-data
        persistentVolumeClaim:
          claimName: agents-data-pvc
      - name: agents-models
        persistentVolumeClaim:
          claimName: agents-models-pvc 