apiVersion: v1
kind: Service
metadata:
  name: {{ include "posey-agents.fullname" . }}
  labels:
    {{- include "posey-agents.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.ingressPortName | default "http" }}
      protocol: TCP
      name: {{ .Values.service.ingressPortName | default "http" }}
  selector:
    {{- include "posey-agents.selectorLabels" . | nindent 4 }} 