{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  # Use the name from values.yaml, falling back to fullname if not specified
  name: {{ .Values.serviceAccount.name | default (include "posey-agents.fullname" .) }}
  labels:
    {{- include "posey-agents.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}