apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: posey-internal-network
  namespace: posey
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: posey
    ports:
    - protocol: TCP 