version: 2.1

# Define this as a setup configuration
setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

# Set up organization-level orbs
orbs-dir: .circleci/orbs
orbs-settings:
  namespace: posey

# Define pipeline parameters that will be passed to the continuation configuration
parameters:
  run-workflow:
    default: true
    type: boolean
  orb-version-type:
    description: "Version type for orb publishing (patch, minor, major)"
    type: enum
    enum: ["patch", "minor", "major"]
    default: "patch"
  run-voyager-workflow:
    type: boolean
    default: false
  run-mcp-workflow:
    type: boolean
    default: false
  run-supertokens-workflow:
    type: boolean
    default: false
  run-agents-workflow:
    type: boolean
    default: false
  run-vector-db-workflow:
    type: boolean
    default: false
  run-postgres-workflow:
    type: boolean
    default: false
  run-couchbase-workflow:
    type: boolean
    default: false
  run-auth-service-workflow:
    description: "Run Auth Service workflow"
    type: boolean
    default: false
  run-cron-service-workflow:
    description: "Run Cron Service workflow"
    type: boolean
    default: false

workflows:
  # Path-based filtering to determine what to build
  path-filtering:
    jobs:
      - path-filtering/filter:
          pre-steps:
            - run:
                name: Install yq
                command: |
                  curl -L https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -o /tmp/yq
                  chmod +x /tmp/yq
                  sudo mv /tmp/yq /usr/local/bin/yq
                  yq --version
            - checkout
            - run:
                name: Detect version bump type from commit message
                command: |
                  # Default is patch
                  VERSION_TYPE="patch"
                  
                  # Get the commit message
                  COMMIT_MSG=$(git log -1 --pretty=%B)
                  
                  # Check for version bump flags in commit message
                  if echo "$COMMIT_MSG" | grep -q "\[major\]"; then
                    VERSION_TYPE="major"
                  elif echo "$COMMIT_MSG" | grep -q "\[minor\]"; then
                    VERSION_TYPE="minor"
                  elif echo "$COMMIT_MSG" | grep -q "\[patch\]"; then
                    VERSION_TYPE="patch"
                  fi
                  
                  echo "Using version type: $VERSION_TYPE"
                  # Pass to the CircleCI configuration
                  echo "export PARAM_ORB_VERSION_TYPE=$VERSION_TYPE" >> $BASH_ENV
          name: check-updated-files
          mapping: |
            # Service code paths
            services/auth/.* run-auth-service-workflow true
            apps/cron/.* run-cron-service-workflow true
            data/postgres/.* run-postgres-workflow true
            data/couchbase/.* run-couchbase-workflow true
            data/vector-db/.* run-vector-db-workflow true
            services/mcp/.* run-mcp-workflow true
            services/supertokens/.* run-supertokens-workflow true
            services/voyager/.* run-voyager-workflow true
            services/agents/.* run-agents-workflow true
            
            # Orb file paths
            .circleci/orbs/service-auth-orb.yml run-auth-service-workflow true
            .circleci/orbs/service-cron-orb.yml run-cron-service-workflow true
            .circleci/orbs/data-postgres-orb.yml run-postgres-workflow true
            .circleci/orbs/data-couchbase-orb.yml run-couchbase-workflow true
            .circleci/orbs/data-vector-db-orb.yml run-vector-db-workflow true
            .circleci/orbs/service-mcp-orb.yml run-mcp-workflow true
            .circleci/orbs/service-supertokens-orb.yml run-supertokens-workflow true
            .circleci/orbs/service-voyager-orb.yml run-voyager-workflow true
            .circleci/orbs/service-agents-orb.yml run-agents-workflow true
            
            # Common orb changes trigger all services
            .circleci/orbs/common-orb.yml run-auth-service-workflow true
            .circleci/orbs/common-orb.yml run-cron-service-workflow true
            .circleci/orbs/common-orb.yml run-postgres-workflow true
            .circleci/orbs/common-orb.yml run-couchbase-workflow true
            .circleci/orbs/common-orb.yml run-vector-db-workflow true
            .circleci/orbs/common-orb.yml run-mcp-workflow true
            .circleci/orbs/common-orb.yml run-supertokens-workflow true
            .circleci/orbs/common-orb.yml run-voyager-workflow true
            .circleci/orbs/common-orb.yml run-agents-workflow true
          base-revision: main
          # This is the path to the configuration file that will be used for the continuation
          config-path: .circleci/continue_config.yml
          post-steps:
            - checkout
            - run:
                name: Update continue_config.yml with version type
                command: |
                  VERSION_TYPE="${PARAM_ORB_VERSION_TYPE:-patch}"
                  echo "Using version type: $VERSION_TYPE for orb publishing"
                  
                  # Create a temp file and update the orb-version-type parameter
                  sed "s/orb-version-type:.*/orb-version-type: \"$VERSION_TYPE\"/" .circleci/continue_config.yml > /tmp/new_config.yml
                  mv /tmp/new_config.yml .circleci/continue_config.yml
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/ 