version: 2.1

# Standard and local orbs
orbs:
  # Standard orbs from the registry
  docker: circleci/docker@2.5.0
  path-filtering: circleci/path-filtering@1.0.0
  cli: circleci/circleci-cli@0.1.9
  
  # Published orbs
  common: posey/common@0.1.5
  data-postgres: posey/data-postgres@0.1.4

# Define the parameters that will be passed from the setup configuration
parameters:
  run-postgres-workflow:
    type: boolean
    default: false
  run-common-change-workflow:
    description: "Run the combined workflow when the common orb changes"
    type: boolean
    default: false

workflows:
  version: 2

  # Postgres workflow
  postgres:
    when: << pipeline.parameters.run-postgres-workflow >>
    jobs:
      - data-postgres/build-postgres:
          context:
            - posey-prod-core
            - posey-prod-data
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Combined workflow for when common orb changes
  all-services:
    when: << pipeline.parameters.run-common-change-workflow >>
    jobs:
      - data-postgres/build-postgres:
          context:
            - posey-prod-core
            - posey-prod-data
