version: 2.1

# Standard and local orbs
orbs:
  # Standard orbs from the registry
  docker: circleci/docker@2.5.0
  path-filtering: circleci/path-filtering@1.0.0
  cli: circleci/circleci-cli@0.1.9
  
  # Published orbs - using volatile for development
  common: posey/common@0.1.1
  service-auth: posey/service-auth@0.1.1
  service-cron: posey/service-cron@0.1.1
  data-postgres: posey/data-postgres@0.1.1
  data-couchbase: posey/data-couchbase@0.1.1
  data-vector-db: posey/data-vector-db@0.1.1
  service-mcp: posey/service-mcp@0.1.1
  service-supertokens: posey/service-supertokens@0.1.1
  service-voyager: posey/service-voyager@0.1.1
  service-agents: posey/service-agents@0.1.1

# Define the parameters that will be passed from the setup configuration
parameters:
  run-voyager-workflow:
    type: boolean
    default: false
  run-mcp-workflow:
    type: boolean
    default: false
  run-supertokens-workflow:
    type: boolean
    default: false
  run-agents-workflow:
    type: boolean
    default: false
  run-vector-db-workflow:
    type: boolean
    default: false
  run-postgres-workflow:
    type: boolean
    default: false
  run-couchbase-workflow:
    type: boolean
    default: false
  run-auth-service-workflow:
    description: "Run Auth Service workflow"
    type: boolean
    default: false
  run-cron-service-workflow:
    description: "Run Cron Service workflow"
    type: boolean
    default: false

workflows:
  version: 2

  # Auth Service workflow
  auth-service:
    when: << pipeline.parameters.run-auth-service-workflow >>
    jobs:
      - build-auth-service:
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Cron Service workflow
  cron-service:
    when: << pipeline.parameters.run-cron-service-workflow >>
    jobs:
      - build-cron-service:
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # MCP Service workflow
  mcp-service:
    when: << pipeline.parameters.run-mcp-workflow >>
    jobs:
      - build-mcp-service:
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # SuperTokens Service workflow
  supertokens-service:
    when: << pipeline.parameters.run-supertokens-workflow >>
    jobs:
      - build-supertokens-service:
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Voyager Service workflow
  voyager-service:
    when: << pipeline.parameters.run-voyager-workflow >>
    jobs:
      - build-voyager-service:
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Agents Service workflow
  agents-service:
    when: << pipeline.parameters.run-agents-workflow >>
    jobs:
      - build-agents-service:
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Postgres workflow
  postgres:
    when: << pipeline.parameters.run-postgres-workflow >>
    jobs:
      - build-postgres:
          context:
            - posey-prod-core
            - posey-prod-data
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Couchbase workflow
  couchbase:
    when: << pipeline.parameters.run-couchbase-workflow >>
    jobs:
      - build-couchbase:
          context:
            - posey-prod-core
            - posey-prod-data
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Vector DB workflow
  vector-db:
    when: << pipeline.parameters.run-vector-db-workflow >>
    jobs:
      - build-vector-db:
          context:
            - posey-prod-core
            - posey-prod-data
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Combined workflow for when common orb changes
  all-services:
    when: << pipeline.parameters.run-auth-service-workflow >> && << pipeline.parameters.run-cron-service-workflow >> && << pipeline.parameters.run-postgres-workflow >> && << pipeline.parameters.run-couchbase-workflow >> && << pipeline.parameters.run-vector-db-workflow >> && << pipeline.parameters.run-mcp-workflow >> && << pipeline.parameters.run-supertokens-workflow >> && << pipeline.parameters.run-voyager-workflow >> && << pipeline.parameters.run-agents-workflow >>
    jobs:
      - build-auth-service:
          context:
            - posey-prod-core
            - posey-prod-services
      - build-cron-service:
          context:
            - posey-prod-core
            - posey-prod-services
      - build-mcp-service:
          context:
            - posey-prod-core
            - posey-prod-services
      - build-supertokens-service:
          context:
            - posey-prod-core
            - posey-prod-services
      - build-voyager-service:
          context:
            - posey-prod-core
            - posey-prod-services
      - build-agents-service:
          context:
            - posey-prod-core
            - posey-prod-services
      - build-postgres:
          context:
            - posey-prod-core
            - posey-prod-data
      - build-couchbase:
          context:
            - posey-prod-core
            - posey-prod-data
      - build-vector-db:
          context:
            - posey-prod-core
            - posey-prod-data 