version: 2.1

# Standard and local orbs
orbs:
  # Standard orbs from the registry
  docker: circleci/docker@2.5.0
  path-filtering: circleci/path-filtering@1.0.0
  cli: circleci/circleci-cli@1.0
  
  # Posey orbs with simplified references
  common: posey/common@1.0
  service-auth: posey/service-auth@1.0
  service-cron: posey/service-cron@1.0
  data-postgres: posey/data-postgres@1.0
  data-couchbase: posey/data-couchbase@1.0
  data-vector-db: posey/data-vector-db@1.0
  service-mcp: posey/service-mcp@1.0
  service-supertokens: posey/service-supertokens@1.0
  service-voyager: posey/service-voyager@1.0
  service-agents: posey/service-agents@1.0

# Define the parameters that will be passed from the setup configuration
parameters:
  run-voyager-workflow:
    type: boolean
    default: false
  run-mcp-workflow:
    type: boolean
    default: false
  run-supertokens-workflow:
    type: boolean
    default: false
  run-agents-workflow:
    type: boolean
    default: false
  run-vector-db-workflow:
    type: boolean
    default: false
  run-postgres-workflow:
    type: boolean
    default: false
  run-couchbase-workflow:
    type: boolean
    default: false
  run-auth-service-workflow:
    description: "Run Auth Service workflow"
    type: boolean
    default: false
  run-cron-service-workflow:
    description: "Run Cron Service workflow"
    type: boolean
    default: false
  run-orb-publishing-workflow:
    description: "Run the workflow to publish orbs"
    type: boolean
    default: false

# Commands for orb publishing
commands:
  create-namespace-if-needed:
    description: "Create the namespace if it doesn't exist"
    parameters:
      namespace:
        type: string
        default: "posey"
    steps:
      - run:
          name: Check if namespace exists and create if needed
          command: |
            if ! circleci namespace list | grep -q "^<< parameters.namespace >> "; then
              echo "Creating namespace: << parameters.namespace >>"
              circleci namespace create << parameters.namespace >> --org-id "${CIRCLE_ORGANIZATION_ID}"
            else
              echo "Namespace << parameters.namespace >> already exists"
            fi

  create-orb-if-needed:
    description: "Create an orb if it doesn't exist"
    parameters:
      namespace:
        type: string
        default: "posey"
      orb-name:
        type: string
    steps:
      - run:
          name: Check if orb exists and create if needed
          command: |
            if ! circleci orb list << parameters.namespace >> | grep -q "^<< parameters.namespace >>/<< parameters.orb-name >> "; then
              echo "Creating orb: << parameters.namespace >>/<< parameters.orb-name >>"
              circleci orb create << parameters.namespace >>/<< parameters.orb-name >>
            else
              echo "Orb << parameters.namespace >>/<< parameters.orb-name >> already exists"
            fi

  publish-orb:
    description: "Publish an orb from a file"
    parameters:
      namespace:
        type: string
        default: "posey"
      orb-name:
        type: string
      orb-file:
        type: string
      is-private:
        type: boolean
        default: false
    steps:
      - run:
          name: Publish orb
          command: |
            # First publish as a dev version
            echo "Publishing dev version of << parameters.namespace >>/<< parameters.orb-name >>"
            PRIVATE_FLAG=""
            if [[ "<< parameters.is-private >>" == "true" ]]; then
              PRIVATE_FLAG="--private"
            fi
            
            DEV_VERSION="dev:$(date +%s)"
            circleci orb publish << parameters.orb-file >> << parameters.namespace >>/<< parameters.orb-name >>@$DEV_VERSION $PRIVATE_FLAG
            
            # Then promote to 'patch' (or 'minor' or 'major' depending on your versioning needs)
            echo "Promoting << parameters.namespace >>/<< parameters.orb-name >> to production version"
            circleci orb publish promote << parameters.namespace >>/<< parameters.orb-name >>@$DEV_VERSION patch $PRIVATE_FLAG

# Jobs for orb publishing
jobs:
  publish-common-orb:
    docker:
      - image: cimg/base:2023.10
    steps:
      - checkout
      - cli/install
      - create-namespace-if-needed
      - create-orb-if-needed:
          orb-name: common
      - publish-orb:
          orb-name: common
          orb-file: .circleci/orbs/common-orb.yml

  publish-service-orbs:
    docker:
      - image: cimg/base:2023.10
    steps:
      - checkout
      - cli/install
      - create-namespace-if-needed
      - run:
          name: Publish all service orbs
          command: |
            # Create and publish each service orb
            for ORB_FILE in .circleci/orbs/service-*-orb.yml; do
              ORB_BASENAME=$(basename "$ORB_FILE" .yml)
              ORB_NAME="${ORB_BASENAME%-orb}"
              
              echo "Creating and publishing $ORB_NAME"
              
              # Create orb if needed
              if ! circleci orb list posey | grep -q "^posey/$ORB_NAME "; then
                echo "Creating orb: posey/$ORB_NAME"
                circleci orb create posey/$ORB_NAME
              else
                echo "Orb posey/$ORB_NAME already exists"
              fi
              
              # Publish dev version
              DEV_VERSION="dev:$(date +%s)"
              circleci orb publish "$ORB_FILE" posey/$ORB_NAME@$DEV_VERSION
              
              # Promote to patch
              circleci orb publish promote posey/$ORB_NAME@$DEV_VERSION patch
            done

  publish-data-orbs:
    docker:
      - image: cimg/base:2023.10
    steps:
      - checkout
      - cli/install
      - create-namespace-if-needed
      - run:
          name: Publish all data orbs
          command: |
            # Create and publish each data orb
            for ORB_FILE in .circleci/orbs/data-*-orb.yml; do
              ORB_BASENAME=$(basename "$ORB_FILE" .yml)
              ORB_NAME="${ORB_BASENAME%-orb}"
              
              echo "Creating and publishing $ORB_NAME"
              
              # Create orb if needed
              if ! circleci orb list posey | grep -q "^posey/$ORB_NAME "; then
                echo "Creating orb: posey/$ORB_NAME"
                circleci orb create posey/$ORB_NAME
              else
                echo "Orb posey/$ORB_NAME already exists"
              fi
              
              # Publish dev version
              DEV_VERSION="dev:$(date +%s)"
              circleci orb publish "$ORB_FILE" posey/$ORB_NAME@$DEV_VERSION
              
              # Promote to patch
              circleci orb publish promote posey/$ORB_NAME@$DEV_VERSION patch
            done

workflows:
  version: 2

  # Orb Publishing workflow
  publish-orbs:
    when: << pipeline.parameters.run-orb-publishing-workflow >>
    jobs:
      - publish-common-orb:
          context: org-global
      - publish-service-orbs:
          requires:
            - publish-common-orb
          context: org-global
      - publish-data-orbs:
          requires:
            - publish-common-orb
          context: org-global

  # Auth Service workflow
  auth-service:
    when: << pipeline.parameters.run-auth-service-workflow >>
    jobs:
      - service-auth/build-auth-service:
          context:
            - org-global
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Cron Service workflow
  cron-service:
    when: << pipeline.parameters.run-cron-service-workflow >>
    jobs:
      - service-cron/build-cron-service:
          context:
            - org-global
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # MCP Service workflow
  mcp-service:
    when: << pipeline.parameters.run-mcp-workflow >>
    jobs:
      - service-mcp/build-mcp-service:
          context:
            - org-global
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # SuperTokens Service workflow
  supertokens-service:
    when: << pipeline.parameters.run-supertokens-workflow >>
    jobs:
      - service-supertokens/build-supertokens-service:
          context:
            - org-global
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Voyager Service workflow
  voyager-service:
    when: << pipeline.parameters.run-voyager-workflow >>
    jobs:
      - service-voyager/build-voyager-service:
          context:
            - org-global
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Agents Service workflow
  agents-service:
    when: << pipeline.parameters.run-agents-workflow >>
    jobs:
      - service-agents/build-agents-service:
          context:
            - org-global
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Postgres workflow
  postgres:
    when: << pipeline.parameters.run-postgres-workflow >>
    jobs:
      - data-postgres/build-postgres:
          context:
            - org-global
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Couchbase workflow
  couchbase:
    when: << pipeline.parameters.run-couchbase-workflow >>
    jobs:
      - data-couchbase/build-couchbase:
          context:
            - org-global
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Vector DB workflow
  vector-db:
    when: << pipeline.parameters.run-vector-db-workflow >>
    jobs:
      - data-vector-db/build-vector-db:
          context:
            - org-global
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/ 