version: 2.1

orbs:
  docker: circleci/docker@2.5.0
  path-filtering: circleci/path-filtering@1.0.0
  cli: circleci/circleci-cli@0.1.9
  
  common: posey/common@0.4.13
  data-postgres: posey/data-postgres@0.4.13
  data-qdrant: posey/data-qdrant@0.3.13
  data-couchbase: posey/data-couchbase@0.4.13
  service-mcp: posey/service-mcp@0.5.26
  service-auth: posey/service-auth@0.1.27
  service-supertokens: posey/service-supertokens@0.1.27
  service-cron: posey/service-cron@0.1.13

parameters:
  run-postgres-workflow:
    type: boolean
    default: false
  run-qdrant-workflow:
    type: boolean
    default: false
  run-couchbase-workflow:
    type: boolean
    default: false
  run-mcp-workflow:
    type: boolean
    default: false
  run-auth-workflow:
    type: boolean
    default: false
  run-supertokens-workflow:
    type: boolean
    default: false
  run-cron-workflow:
    type: boolean
    default: false
  run-voyager-workflow:
    type: boolean
    default: false
  run-common-change-workflow:
    description: "Run the combined workflow when the common orb changes"
    type: boolean
    default: false
  orb-version-type:
    description: "Version type for orb publishing (patch, minor, major)"
    type: enum
    enum: ["patch", "minor", "major"]
    default: "patch"

workflows:
  version: 2

  ############################################################
  # DATA SERVICES
  ############################################################

  postgres:
    when: << pipeline.parameters.run-postgres-workflow >>
    jobs:
      - data-postgres/build-postgres:
          context:
            - posey-prod-core
            - posey-prod-data
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  qdrant:
    when: << pipeline.parameters.run-qdrant-workflow >>
    jobs:
      - data-qdrant/build-qdrant:
          context:
            - posey-prod-core
            - posey-prod-data
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  couchbase:
    when: << pipeline.parameters.run-couchbase-workflow >>
    jobs:
      - data-couchbase/build-couchbase:
          context:
            - posey-prod-core
            - posey-prod-data
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  ############################################################
  # CORE SERVICES
  ############################################################

  mcp:
    when: << pipeline.parameters.run-mcp-workflow >>
    jobs:
      - service-mcp/build-mcp:
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  auth:
    when: << pipeline.parameters.run-auth-workflow >>
    jobs:
      - service-auth/build-auth:
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  supertokens:
    when: << pipeline.parameters.run-supertokens-workflow >>
    jobs:
      - service-supertokens/build-supertokens:
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  cron:
    when: << pipeline.parameters.run-cron-workflow >>
    jobs:
      - service-cron/build-cron:
          name: build-cron
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  # Add the voyager workflow
  voyager:
    when: << pipeline.parameters.run-voyager-workflow >>
    jobs:
      - service-cron/build-voyager:
          name: build-voyager
          context:
            - posey-prod-core
            - posey-prod-services
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

  all-services:
    when: << pipeline.parameters.run-common-change-workflow >>
    jobs:
      - data-postgres/build-postgres:
          context:
            - posey-prod-core
            - posey-prod-data
      - data-qdrant/build-qdrant:
          context:
            - posey-prod-core
            - posey-prod-data
      - data-couchbase/build-couchbase:
          context:
            - posey-prod-core
            - posey-prod-data
      - service-mcp/build-mcp:
          context:
            - posey-prod-core
            - posey-prod-services
      - service-auth/build-auth:
          context:
            - posey-prod-core
            - posey-prod-services
      - service-supertokens/build-supertokens:
          context:
            - posey-prod-core
            - posey-prod-services
      - service-cron/build-cron:
          name: build-cron-common
          context:
            - posey-prod-core
            - posey-prod-services
