apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared/namespace.yaml
  - shared/network-policy.yaml
  - shared/config-map.yaml
  - shared/secrets.yaml
  - shared/persistent-volumes.yaml
  - agents/deployment.yaml
  - agents/service.yaml
  - auth/deployment.yaml
  - auth/service.yaml
  - cron/deployment.yaml
  - cron/service.yaml
  - supertokens/deployment.yaml
  - supertokens/service.yaml
  - voyager/deployment.yaml
  - voyager/service.yaml
  - mcp/deployment.yaml
  - mcp/service.yaml 