apiVersion: apps/v1
kind: Deployment
metadata:
  name: posey-auth-local-debug
  # You might want a namespace, but default is fine for local debug
  # namespace: posey 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posey-auth-local-debug
  template:
    metadata:
      labels:
        app: posey-auth-local-debug
    spec:
      containers:
      - name: posey-auth
        image: posey-auth-local:debug # Use locally built image
        imagePullPolicy: Never # Don't try to pull from registry
        ports:
        - containerPort: 9999
        env:
        # --- IMPORTANT ---
        # Add ALL environment variables needed by your auth service here.
        # These should mirror your services/core/auth/.env.local
        # Example:
        - name: NODE_ENV
          value: "production" 
        - name: SUPERTOKENS_API_KEY # Example, replace with actual needed vars
          value: "YOUR_SUPERTOKENS_KEY_HERE" # Replace with value from .env.local or use Secrets/ConfigMaps
        - name: SUPERTOKENS_CONNECTION_URI # Example
          value: "http://supertokens-service:3567" # Adjust if needed for local K8s
        - name: DATABASE_URL # Example
          value: "postgresql://user:password@postgres-service:5432/authdb" # Adjust if needed for local K8s
        # Add other variables like CORS origins, etc.
        
        # --- CRITICAL ---
        # DO NOT define 'command' or 'args' here, 
        # so that it uses the CMD from your Dockerfile
        # command: [] 
        # args: [] 