export const MAX_TOKENS_XS = 4096;
export const MAX_TOKENS_SMALL = MAX_TOKENS_XS * 2;
export const MAX_TOKENS_MEDIUM = MAX_TOKENS_SMALL * 2;
export const MAX_TOKENS_LARGE = MAX_TOKENS_MEDIUM * 2;
export const MAX_TOKENS_XL = MAX_TOKENS_LARGE * 2;

export const DEFAULT_MODEL_TEMP = 1;
export const DEFAULT_MODEL_MAX_TOKENS = 16384;
export const DEFAULT_MODEL_CONTEXT_WINDOW = 128000;
