apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensures resources are deleted when app is deleted
  labels:
    app.kubernetes.io/component: cluster-addon
    app.kubernetes.io/part-of: posey
spec:
  project: default # Or a specific project for cluster addons

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: "2.16.*" # Use a specific version range or version
    helm:
      releaseName: sealed-secrets
      # Optional: Add values here if needed to customize the installation
      # values: |
      #   someValue: true

  destination:
    server: https://kubernetes.default.svc
    # Install the controller in kube-system
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Creates kube-system if it doesn't exist (it should)
      # Important: Allow cluster-scoped resources like CRDs
      - ServerSideApply=true # Recommended for CRDs and controllers
      - ApplyOutOfSyncOnly=true 