apiVersion: 1

providers:
  - name: 'Docker Swarm'
    orgId: 1
    folder: 'Docker'
    folderUid: ''
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards/docker-swarm
