global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'node-services'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:9464']  # Default Node.js exporter port

remote_write:
  - url: "http://mimir:9009/api/v1/push"
    name: mimir 