server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 100_000_000
    block_retention: 168h

storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: 0.05
      index_downsample_bytes: 1000
      encoding: zstd
    local:
      path: /tmp/tempo
    pool:
      max_workers: 100
      queue_depth: 10000 