apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # Production Let's Encrypt API
    server: https://acme-v02.api.letsencrypt.org/directory
    email: server-admin@posey.ai
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token 