version: 2.1

description: "Common orb with shared executors and commands for Posey services"

executors:
  docker-builder:
    docker:
      - image: cimg/base:current
    resource_class: large
    environment:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      YARN_VERBOSE: true
      YARN_ENABLE_PROGRESS_BARS: true
      YARN_LOG_LEVEL: info

commands:
  setup-buildx:
    description: "Set up Docker Buildx"
    steps:
      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --use --name=multiplatform-builder --driver=docker-container --driver-opt=network=host --buildkitd-flags="--allow-insecure-entitlement network.host" --bootstrap
            docker buildx inspect --bootstrap

  setup-common:
    description: "Setup common environment for Docker builds and basic CI tasks"
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24 # Consider using a newer version if available/needed
          docker_layer_caching: true
      - run:
          name: Configure git
          command: |
            git config --global url."https://github.com/".insteadOf git@github.com:
            git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - run:
          name: Configure network
          command: |
            echo "Setting up network optimizations..."
            # Note: Modifying resolv.conf directly might be overwritten. Consider systemd-resolved if available.
            echo "options single-request-reopen" | sudo tee -a /etc/resolv.conf
            echo "options timeout:10" | sudo tee -a /etc/resolv.conf
            echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
            echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf
            # Increase TCP performance
            # Ensure these settings are appropriate for the environment
            sudo sysctl -w net.ipv4.tcp_slow_start_after_idle=0
            sudo sysctl -w net.ipv4.tcp_fastopen=3
      - run:
          name: Install Helm
          command: |
            echo "Installing Helm..."
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh
            helm version
      - run:
          name: Build Helm Chart Dependencies
          command: |
            echo "Looking for charts with dependencies in k8s/charts..."
            find k8s/charts -name Chart.yaml -exec grep -l '^dependencies:' {} \; | while read chart_file; do
              chart_dir=$(dirname "$chart_file")
              echo "Building dependencies for $chart_dir"
              # Use helm dependency build for a clean state in CI
              helm dependency build "$chart_dir" || { echo "Helm dependency build failed for $chart_dir"; exit 1; }
            done
            echo "Finished building Helm dependencies."
      - run: # Add Docker Hub login
          name: Log in to Docker Hub
          command: |
            if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_TOKEN" ]; then
               echo "Docker Hub credentials (DOCKERHUB_USERNAME, DOCKERHUB_TOKEN) not found. Skipping login."
            else
               echo "Logging into Docker Hub..."
               echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            fi
      - setup-buildx # Setup Buildx, needed for building images 