version: 2.1

description: "Orb for building and deploying the Postgres service"

# Use the common orb for shared executors and commands
orbs:
  common: posey/common@0.0.13

jobs:
  build-postgres:
    executor: common/docker-builder
    steps:
      - common/setup-common
      - run:
          name: Pull existing images for cache
          command: |
            echo "Pulling existing images for caching..."
            docker pull registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:latest || echo "No latest image found"
            docker pull registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:buildcache || echo "No buildcache image found" 
            docker pull registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:PRODUCTION || echo "No PRODUCTION image found"
      - run:
          name: Build Postgres Service
          no_output_timeout: 30m
          command: |
            echo "Building postgres service..."
            
            # Create logs directory
            mkdir -p build-logs
            
            # Try the build up to 3 times to handle network failures
            max_attempts=3
            attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "Build attempt $attempt of $max_attempts"
              
              # Only build for amd64 to speed up build time
              set -o pipefail && DOCKER_BUILDKIT=1 docker buildx build \
                --platform linux/amd64 \
                --build-arg BUILDKIT_INLINE_CACHE=1 \
                --build-arg NODE_ENV=production \
                --progress=plain \
                --memory=8g \
                --cache-from type=registry,ref=registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:buildcache \
                --cache-from registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:latest \
                --cache-from registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:PRODUCTION \
                --cache-to type=registry,ref=registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:buildcache,mode=max \
                -t registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:latest \
                -t registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:PRODUCTION \
                -t registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-postgres:$(echo $CIRCLE_SHA1 | cut -c1-7) \
                -f data/postgres/Dockerfile \
                --push \
                ./data/postgres 2>&1 | tee build-logs/build-attempt-$attempt.log
                
              if [ ${PIPESTATUS[0]} -eq 0 ]; then
                echo "Build succeeded on attempt $attempt"
                cp build-logs/build-attempt-$attempt.log build-logs/build.log
                break
              else
                echo "Build failed on attempt $attempt"
                if [ $attempt -eq $max_attempts ]; then
                  echo "All build attempts failed"
                  cp build-logs/build-attempt-$attempt.log build-logs/build.log
                  exit 1
                fi
                attempt=$((attempt+1))
                echo "Waiting 60 seconds before next attempt..."
                sleep 60
              fi
            done
      - common/install-kubectl
      - common/setup-kubeconfig
      - run:
          name: Trigger ArgoCD sync for Postgres
          command: |
            # Debug environment
            echo "Current directory: $(pwd)"
            echo "Available disk space:"
            df -h
            
            # Check if ArgoCD variables are set (safely)
            if [ -z "${ARGOCD_SERVER}" ]; then
              echo "ERROR: ARGOCD_SERVER environment variable is not set"
              exit 1
            else
              echo "ARGOCD_SERVER is set to: ${ARGOCD_SERVER}"
            fi
            
            if [ -z "${ARGOCD_TOKEN}" ]; then
              echo "ERROR: ARGOCD_TOKEN environment variable is not set"
              exit 1
            else
              echo "ARGOCD_TOKEN is set (token length: ${#ARGOCD_TOKEN})"
            fi
            
            # Create temp directory for downloads
            TEMP_DIR=$(mktemp -d)
            echo "Using temporary directory: ${TEMP_DIR}"
            cd ${TEMP_DIR}
            
            # Install argocd CLI with verbose output and retry
            echo "Downloading ArgoCD CLI..."
            curl -v --retry 3 --retry-delay 5 -L -o argocd.download https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            
            # Check if download was successful
            if [ $? -ne 0 ]; then
              echo "ERROR: Failed to download ArgoCD CLI"
              # Try specific version as fallback
              echo "Trying specific version instead..."
              curl -v --retry 3 --retry-delay 5 -L -o argocd.download https://github.com/argoproj/argo-cd/releases/download/v2.8.4/argocd-linux-amd64
              
              if [ $? -ne 0 ]; then
                echo "ERROR: Failed to download ArgoCD CLI (specific version)"
                exit 1
              fi
            fi
            
            echo "ArgoCD CLI downloaded successfully. Size: $(ls -lh argocd.download | awk '{print $5}')"
            chmod +x argocd.download
            sudo mv argocd.download /usr/local/bin/argocd
            cd -
            
            echo "ArgoCD CLI version:"
            argocd version --client
            
            # Test the server connection
            echo "Testing connection to ArgoCD server..."
            curl -k -s ${ARGOCD_SERVER}/api/version | grep -q "version" && echo "Server connection successful" || echo "Server connection failed"
            
            # Log in to ArgoCD (using token auth)
            echo "Logging in to ArgoCD server..."
            argocd login ${ARGOCD_SERVER} --auth-token ${ARGOCD_TOKEN} --grpc-web --insecure
            
            # Trigger sync for the postgres application
            echo "Triggering sync for posey-postgres..."
            argocd app sync posey-postgres --force
            
            # Wait for sync to complete
            echo "Waiting for sync to complete..."
            argocd app wait posey-postgres --health --timeout 300
      - store_artifacts:
          path: build-logs
          destination: build-logs 