version: 2.1

description: "Orb for building and deploying the Postgres service"

# Use the common orb for shared executors and commands
orbs:
  common: posey/common@0.4.8

jobs:
  build-postgres:
    executor: common/docker-builder
    steps:
      - common/setup-common
      - run:
          name: Pull existing images for cache
          command: |
            echo "Pulling existing images for caching..."
            docker pull docker.io/poseylabs/posey-postgres:latest || echo "No latest image found"
            docker pull docker.io/poseylabs/posey-postgres:buildcache || echo "No buildcache image found"
            docker pull docker.io/poseylabs/posey-postgres:PRODUCTION || echo "No PRODUCTION image found"
      - run:
          name: Build Postgres Service
          no_output_timeout: 30m
          command: |
            echo "Building postgres service..."
            
            # Create logs directory
            mkdir -p build-logs
            
            # Try the build up to 3 times to handle network failures
            max_attempts=3
            attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "Build attempt $attempt of $max_attempts"
              
              # Build for both amd64 and arm64
              set -o pipefail && DOCKER_BUILDKIT=1 docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --build-arg BUILDKIT_INLINE_CACHE=1 \
                --build-arg NODE_ENV=production \
                --progress=plain \
                --memory=8g \
                --cache-from type=registry,ref=docker.io/poseylabs/posey-postgres:buildcache \
                --cache-from docker.io/poseylabs/posey-postgres:latest \
                --cache-from docker.io/poseylabs/posey-postgres:PRODUCTION \
                --cache-to type=registry,ref=docker.io/poseylabs/posey-postgres:buildcache,mode=max \
                -t docker.io/poseylabs/posey-postgres:latest \
                -t docker.io/poseylabs/posey-postgres:PRODUCTION \
                -t docker.io/poseylabs/posey-postgres:$(echo $CIRCLE_SHA1 | cut -c1-7) \
                -f services/data/postgres/Dockerfile \
                --push \
                ./services/data/postgres 2>&1 | tee build-logs/build-attempt-$attempt.log
                
              if [ ${PIPESTATUS[0]} -eq 0 ]; then
                echo "Build succeeded on attempt $attempt"
                cp build-logs/build-attempt-$attempt.log build-logs/build.log
                break
              else
                echo "Build failed on attempt $attempt"
                if [ $attempt -eq $max_attempts ]; then
                  echo "All build attempts failed"
                  cp build-logs/build-attempt-$attempt.log build-logs/build.log
                  exit 1
                fi
                attempt=$((attempt+1))
                echo "Waiting 60 seconds before next attempt..."
                sleep 60
              fi
            done
      - run:
          name: Trigger ArgoCD sync for Postgres
          # Increased timeout for the whole step to accommodate script execution + wait time
          no_output_timeout: 10m 
          command: |
            # Ensure the script is executable
            chmod +x .circleci/scripts/trigger-argocd-sync.sh
            
            # Execute the script, passing the application name
            .circleci/scripts/trigger-argocd-sync.sh posey-postgres

      - store_artifacts:
          path: build-logs
          destination: build-logs 