version: 2.1

description: "Orb for building and deploying the Voyager service"

# Use the common orb for shared executors and commands
orbs:
  common: posey/common@0.5.0 # Use the same version as mcp orb for consistency

jobs:
  build-voyager: # Renamed job
    executor: common/docker-builder
    steps:
      - common/setup-common
      - run:
          name: Pull existing images for cache
          command: |
            echo "Pulling existing images for caching..."
            docker pull docker.io/poseylabs/posey-voyager:latest || echo "No latest image found"
            docker pull docker.io/poseylabs/posey-voyager:buildcache || echo "No buildcache image found"
            docker pull docker.io/poseylabs/posey-voyager:PRODUCTION || echo "No PRODUCTION image found"
      - run:
          name: Build Voyager Service # Updated service name
          no_output_timeout: 30m
          command: |
            echo "Building voyager service..." # Updated echo message

            # Create logs directory
            mkdir -p build-logs

            # Try the build up to 3 times to handle network failures
            max_attempts=3
            attempt=1

            while [ $attempt -le $max_attempts ]; do
              echo "Build attempt $attempt of $max_attempts"

              # Build for both amd64 and arm64
              set -o pipefail && DOCKER_BUILDKIT=1 docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --build-arg BUILDKIT_INLINE_CACHE=1 \
                --build-arg NODE_ENV=production \
                --progress=plain \
                --memory=8g \
                --cache-from type=registry,ref=docker.io/poseylabs/posey-voyager:buildcache \
                --cache-from docker.io/poseylabs/posey-voyager:latest \
                --cache-from docker.io/poseylabs/posey-voyager:PRODUCTION \
                --cache-to type=registry,ref=docker.io/poseylabs/posey-voyager:buildcache,mode=max \
                -t docker.io/poseylabs/posey-voyager:latest \
                -t docker.io/poseylabs/posey-voyager:PRODUCTION \
                -t docker.io/poseylabs/posey-voyager:$(echo $CIRCLE_SHA1 | cut -c1-7) \
                -f services/core/voyager/Dockerfile \
                --push \
                ./services/core/voyager 2>&1 | tee build-logs/build-attempt-$attempt.log # Updated path and Dockerfile location

              if [ ${PIPESTATUS[0]} -eq 0 ]; then
                echo "Build succeeded on attempt $attempt"
                cp build-logs/build-attempt-$attempt.log build-logs/build.log
                break
              else
                echo "Build failed on attempt $attempt"
                if [ $attempt -eq $max_attempts ]; then
                  echo "All build attempts failed"
                  cp build-logs/build-attempt-$attempt.log build-logs/build.log
                  exit 1
                fi
                attempt=$((attempt+1))
                echo "Waiting 60 seconds before next attempt..."
                sleep 60
              fi
            done
      - run:
          name: Trigger ArgoCD sync for Voyager # Updated service name
          no_output_timeout: 10m
          command: |
            # Ensure the script is executable
            chmod +x .circleci/scripts/trigger-argocd-sync.sh

            # Execute the script, passing the application name
            .circleci/scripts/trigger-argocd-sync.sh posey-voyager # Updated application name

      - store_artifacts:
          path: build-logs
          destination: build-logs 