version: 2.1

description: "Orb for building and deploying the Voyager service"

# Use the common orb for shared executors and commands
orbs:
  common: posey/common@0.0.13

jobs:
  build-voyager-service:
    executor: common/docker-builder
    steps:
      - common/setup-common
      - run:
          name: Pull existing images for cache
          command: |
            echo "Pulling existing images for caching..."
            docker pull registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:latest || echo "No latest image found"
            docker pull registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:buildcache || echo "No buildcache image found" 
            docker pull registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:PRODUCTION || echo "No PRODUCTION image found"
      - run:
          name: Build Voyager Service
          no_output_timeout: 45m
          command: |
            echo "Building voyager service..."
            
            # Create build logs directory
            mkdir -p build-logs
            
            # Try the build up to 3 times to handle network failures
            max_attempts=3
            attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "Build attempt $attempt of $max_attempts"
              
              # Only build for amd64 to speed up build time
              set -o pipefail && DOCKER_BUILDKIT=1 docker buildx build \
                --platform linux/amd64 \
                --build-arg BUILDKIT_INLINE_CACHE=1 \
                --build-arg PLAYWRIGHT_BROWSERS_PATH=/home/voyager/.cache/ms-playwright \
                --build-arg PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 \
                --progress=plain \
                --memory=8g \
                --cache-from type=registry,ref=registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:buildcache \
                --cache-from registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:latest \
                --cache-from registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:PRODUCTION \
                --cache-to type=registry,ref=registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:buildcache,mode=max \
                -t registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:latest \
                -t registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:PRODUCTION \
                -t registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-voyager:$(echo $CIRCLE_SHA1 | cut -c1-7) \
                -f services/voyager/Dockerfile \
                --push \
                ./services/voyager 2>&1 | tee build-logs/build-attempt-$attempt.log
                
              if [ ${PIPESTATUS[0]} -eq 0 ]; then
                echo "Build succeeded on attempt $attempt"
                cp build-logs/build-attempt-$attempt.log build-logs/build.log
                break
              else
                echo "Build failed on attempt $attempt"
                if [ $attempt -eq $max_attempts ]; then
                  echo "All build attempts failed"
                  cp build-logs/build-attempt-$attempt.log build-logs/build.log
                  exit 1
                fi
                attempt=$((attempt+1))
                echo "Waiting 60 seconds before next attempt..."
                sleep 60
              fi
            done
      - common/install-kubectl
      - common/setup-kubeconfig
      - run:
          name: Trigger ArgoCD sync for Voyager Service
          command: |
            # Install argocd CLI if needed
            curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            chmod +x argocd
            sudo mv argocd /usr/local/bin/
            
            # Log in to ArgoCD (using token auth)
            argocd login ${ARGOCD_SERVER} --auth-token ${ARGOCD_TOKEN} --grpc-web
            
            # Trigger sync for the voyager application
            argocd app sync posey-voyager --force
            
            # Wait for sync to complete
            argocd app wait posey-voyager --health --timeout 300
      - store_artifacts:
          path: build-logs
          destination: build-logs 