version: 2.1

description: "Orb for building and deploying the Auth service"

# We'll use the common orb for executors and shared commands
orbs:
  common: posey/common@1.0

jobs:
  build-auth-service:
    executor: common/docker-builder
    steps:
      - common/setup-common
      - run:
          name: Pull existing images for cache
          command: |
            echo "Pulling existing images for caching..."
            docker pull registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:latest || echo "No latest image found"
            docker pull registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:buildcache || echo "No buildcache image found" 
            docker pull registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:PRODUCTION || echo "No PRODUCTION image found"
      - run:
          name: Build Auth Service
          no_output_timeout: 60m
          command: |
            echo "Building auth service..."
            
            # Create yarn logs directory
            mkdir -p yarn-logs
            
            # Try the build up to 3 times to handle network failures
            max_attempts=3
            attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "Build attempt $attempt of $max_attempts"
              
              # Only build for amd64 to speed up build time
              set -o pipefail && DOCKER_BUILDKIT=1 docker buildx build \
                --platform linux/amd64 \
                --build-arg BUILDKIT_INLINE_CACHE=1 \
                --build-arg NODE_ENV=production \
                --build-arg BUILDKIT_MAX_PARALLELISM=4 \
                --build-arg YARN_ENABLE_TELEMETRY=false \
                --build-arg YARN_ENABLE_PROGRESS_BARS=true \
                --build-arg YARN_VERBOSE=true \
                --build-arg DEBUG="yarn*,pnp*" \
                --build-arg YARN_LOG_LEVEL=info \
                --build-arg YARN_COLORS=true \
                --progress=plain \
                --memory=12g \
                --cache-from type=registry,ref=registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:buildcache \
                --cache-from registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:latest \
                --cache-from registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:PRODUCTION \
                --cache-to type=registry,ref=registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:buildcache,mode=max \
                -t registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:latest \
                -t registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:PRODUCTION \
                -t registry.digitalocean.com/${DO_REGISTRY_NAME}/posey-auth:$(echo $CIRCLE_SHA1 | cut -c1-7) \
                -f services/auth/Dockerfile \
                --push \
                . 2>&1 | tee yarn-logs/build-attempt-$attempt.log
                
              if [ ${PIPESTATUS[0]} -eq 0 ]; then
                echo "Build succeeded on attempt $attempt"
                cp yarn-logs/build-attempt-$attempt.log yarn-logs/build.log
                break
              else
                echo "Build failed on attempt $attempt"
                if [ $attempt -eq $max_attempts ]; then
                  echo "All build attempts failed"
                  cp yarn-logs/build-attempt-$attempt.log yarn-logs/build.log
                  exit 1
                fi
                attempt=$((attempt+1))
                echo "Waiting 60 seconds before next attempt..."
                sleep 60
              fi
            done
      - common/install-kubectl
      - common/setup-kubeconfig
      - run:
          name: Trigger ArgoCD sync for Auth
          command: |
            # Install argocd CLI if needed
            curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            chmod +x argocd
            sudo mv argocd /usr/local/bin/
            
            # Log in to ArgoCD (using token auth)
            argocd login ${ARGOCD_SERVER} --auth-token ${ARGOCD_TOKEN} --grpc-web
            
            # Trigger sync for the auth application
            argocd app sync posey-auth --force
            
            # Wait for sync to complete
            argocd app wait posey-auth --health --timeout 300
      - store_artifacts:
          path: yarn-logs
          destination: yarn-logs 