apiVersion: v1
kind: Service
metadata:
  name: posey-couchbase
  namespace: default
  labels:
    app: posey-couchbase
    tier: database
spec:
  # Selector matches the pods created by the StatefulSet
  selector:
    app: posey-couchbase
  # Port mapping
  ports:
  - port: 8091          # Web UI
    targetPort: 8091
    name: web
  - port: 8092          # API
    targetPort: 8092
    name: api
  - port: 8093          # Query
    targetPort: 8093
    name: query
  - port: 8094          # Search
    targetPort: 8094
    name: search
  - port: 11210         # Data
    targetPort: 11210
    name: data
  # ClusterIP makes the service only accessible within the cluster
  type: ClusterIP 