apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchbase-data
  namespace: default
  labels:
    app: posey-couchbase
    tier: database
spec:
  # ReadWriteOnce means the volume can be mounted as read-write by a single node
  accessModes:
    - ReadWriteOnce
  # Request 30Gi of storage for Couchbase
  resources:
    requests:
      storage: 30Gi
  # Digital Ocean's storage class for block storage
  storageClassName: do-block-storage 