apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: posey-couchbase
  namespace: default
  labels:
    app: posey-couchbase
    tier: database
spec:
  serviceName: posey-couchbase
  replicas: 1  # Single replica for Couchbase (consider HA setup for production)
  selector:
    matchLabels:
      app: posey-couchbase
  template:
    metadata:
      labels:
        app: posey-couchbase
        tier: database
    spec:
      containers:
      - name: couchbase
        image: couchbase/server:7.2.0  # Using stable version
        ports:
        - containerPort: 8091
          name: web
        - containerPort: 8092
          name: api
        - containerPort: 8093
          name: query
        - containerPort: 8094
          name: search
        - containerPort: 11210
          name: data
        # Resource limits and requests
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: CB_REST_USERNAME
          valueFrom:
            secretKeyRef:
              name: couchbase-credentials
              key: COUCHBASE_USER
        - name: CB_REST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchbase-credentials
              key: COUCHBASE_PASSWORD
        # Volume mounting for persistent data
        volumeMounts:
        - name: couchbase-data
          mountPath: /opt/couchbase/var
        # Liveness probe to check if Couchbase is running
        livenessProbe:
          httpGet:
            path: /ui/index.html
            port: 8091
          initialDelaySeconds: 60  # Couchbase can take some time to start
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        # Readiness probe to check if Couchbase is ready to accept connections
        readinessProbe:
          httpGet:
            path: /ui/index.html
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      # Init container to set appropriate Couchbase settings
      initContainers:
      - name: init-couchbase
        image: couchbase/server:7.2.0
        command: ["sh", "-c", "chmod -R 777 /opt/couchbase/var"]
        volumeMounts:
        - name: couchbase-data
          mountPath: /opt/couchbase/var
      volumes:
      - name: couchbase-data
        persistentVolumeClaim:
          claimName: couchbase-data 