apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resources that should be applied together
resources:
  - couchbase-pvc.yaml
  - couchbase-statefulset.yaml
  - couchbase-service.yaml
  - couchbase-setup-job.yaml

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/name: couchbase
  app.kubernetes.io/part-of: posey
  app.kubernetes.io/managed-by: kustomize
  tier: database 