apiVersion: v1
kind: ConfigMap
metadata:
  name: posey-shared-env
  namespace: posey
data:
  AGENTS_SERVICE_URL: "http://posey-agents:5555"
  NODE_ENV: "development"
  COUCHBASE_USER: "admin"
  COUCHBASE_PASSWORD: "password"
  COUCHBASE_BUCKET: "posey"
  COUCHBASE_URL: "couchbase://couchbase"
  COUCHBASE_SCOPE: "_default"
  COUCHBASE_COLLECTION: "_default"
  CRON_PORT: "2222"
  EMBEDDING_MODEL: "BAAI/bge-large-en-v1.5"
  EMBEDDING_CACHE_DIR: "/app/models"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  PYTHONPATH: "/app/service"
  QDRANT_HOST: "http://posey-qdrant:1111"
  QDRANT_PORT: "1111"
  VOYAGER_PORT: "7777"
  VOYAGER_DOMAIN: "localhost" 