apiVersion: apps/v1
kind: Deployment
metadata:
  name: posey-mcp
  namespace: posey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posey-mcp
  template:
    metadata:
      labels:
        app: posey-mcp
    spec:
      containers:
      - name: posey-mcp
        image: registry.digitalocean.com/posey/posey-mcp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
        resources:
          limits:
            memory: 1Gi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
        envFrom:
        - configMapRef:
            name: posey-shared-env
        - secretRef:
            name: posey-secrets
        volumeMounts:
        - name: mcp-data
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: mcp-data
        persistentVolumeClaim:
          claimName: mcp-data-pvc 