apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resources that should be applied together
resources:
  - postgres-statefulset.yaml
  - postgres-service.yaml

# Note: We're not using commonLabels because it's deprecated
# The labels are already defined in the individual resources

# Add annotations but don't change selectors
commonAnnotations:
  app.kubernetes.io/part-of: posey
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/created-by: github-actions
