apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resources that should be applied together
resources:
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/part-of: posey
  app.kubernetes.io/managed-by: kustomize 