apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resources that should be applied together
resources:
  - postgres-statefulset.yaml
  - postgres-service.yaml

# Common labels to apply to all resources
labels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/part-of: posey
  app.kubernetes.io/managed-by: kustomize

# Note: We are not including postgres-secret.yaml here because
# it's being created via the GitHub Actions workflow 