apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resources that should be applied together
resources:
  - postgres-statefulset.yaml
  - postgres-service.yaml

# Common labels applied to all resources
commonLabels:
  app: posey-postgres
  tier: database
