apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: default
spec:
  # ReadWriteOnce means the volume can be mounted as read-write by a single node
  accessModes:
    - ReadWriteOnce
  # Request 10Gi of storage for the database
  resources:
    requests:
      storage: 10Gi
  # Digital Ocean's storage class for block storage
  # This is specific to Digital Ocean - may need adjustment for other providers
  storageClassName: do-block-storage 