apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: {{ .Release.Name }}-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-auth
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-auth
    spec:
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: auth
          {{- if .Values.devMode }}
          # In dev mode, use a standard node image for testing
          image: "node:18-alpine"
          command: ["node"]
          args: ["-e", "console.log('Auth Service Mock running on port {{ .Values.services.auth.port }}'); const http = require('http'); const server = http.createServer((req, res) => { res.writeHead(200); if (req.url === '/health') { res.end('OK'); } else { res.end('Auth Service Mock'); } }); server.listen({{ .Values.services.auth.port }});"]
          {{- else }}
          image: "{{ .Values.image.registry }}/posey-auth:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.auth.port }}
              name: http
          env:
            - name: NODE_ENV
              value: {{ .Values.environment.nodeEnv | quote }}
            - name: DEBUG
              value: {{ .Values.environment.debug | quote }}
            - name: PORT
              value: {{ .Values.services.auth.port | quote }}
            - name: DATABASE_URL
              value: {{ .Values.databases.postgres.dsnSupertokens | quote }}
            - name: API_DOMAIN
              value: {{ .Values.services.auth.apiDomain | quote }}
            - name: SUPERTOKENS_CONNECTION_URI
              value: {{ .Values.services.superTokens.connectionUri | quote }}
            - name: WEBSITE_DOMAIN
              value: {{ .Values.services.ui.baseUrl | quote }}
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-api-secrets
                  key: jwt-secret-key
                  optional: true
            - name: SUPERTOKENS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-api-secrets
                  key: supertokens-api-key
                  optional: true
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5 