apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: posey-postgres
    tier: database
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.databases.postgres.password | b64enc }} 