"""Your detailed migration message here

Revision ID: ecd92f3ec52a
Revises: 66a33d61a3f0
Create Date: 2025-04-13 14:25:26.773111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd92f3ec52a'
down_revision: Union[str, None] = '66a33d61a3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.create_index('idx_projects_agent', 'projects', ['agent_id'], unique=False)
    op.create_foreign_key('projects_agent_id_fkey', 'projects', 'agents', ['agent_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_agent_id_fkey', 'projects', type_='foreignkey')
    op.drop_index('idx_projects_agent', table_name='projects')
    op.drop_column('projects', 'agent_id')
    # ### end Alembic commands ###
