apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: posey-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: posey-ingress
spec:
  project: posey
  source:
    repoURL: https://github.com/yourusername/posey.git  # Replace with your actual repo URL
    targetRevision: HEAD
    path: k8s/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: posey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  # Ignore differences in annotations managed by cert-manager
  - group: networking.k8s.io
    kind: Ingress
    jsonPointers:
    - /metadata/annotations/cert-manager.io~1certificate-name 