apiVersion: apps/v1
kind: Deployment
metadata:
  name: posey-agents
  namespace: posey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posey-agents
  template:
    metadata:
      labels:
        app: posey-agents
    spec:
      containers:
      - name: posey-agents
        image: posey-agents:latest  # You'll need to build and push this image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5555
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.5"
        envFrom:
        - configMapRef:
            name: posey-shared-env
        - secretRef:
            name: posey-secrets
        volumeMounts:
        - name: agents-data
          mountPath: /app/data
        - name: agents-models
          mountPath: /app/models
        livenessProbe:
          httpGet:
            path: /health
            port: 5555
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5555"]
      volumes:
      - name: agents-data
        persistentVolumeClaim:
          claimName: agents-data-pvc
      - name: agents-models
        persistentVolumeClaim:
          claimName: agents-models-pvc 