apiVersion: apps/v1
kind: Deployment
metadata:
  name: posey-graphql
  namespace: default
  labels:
    app: posey-graphql
    tier: auth
    service-type: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posey-graphql
  template:
    metadata:
      labels:
        app: posey-graphql
        tier: auth
        service-type: auth
    spec:
      containers:
      - name: hasura
        image: hasura/graphql-engine:v2.36.0
        ports:
        - containerPort: 8080
          name: graphql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hasura-credentials
              key: HASURA_GRAPHQL_DATABASE_URL
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-credentials
              key: HASURA_ADMIN_SECRET
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        - name: HASURA_GRAPHQL_DEV_MODE
          value: "false"
        - name: HASURA_GRAPHQL_LOG_LEVEL
          value: "info"
        - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
          value: "startup, http-log, webhook-log, websocket-log, query-log"
        # Liveness probe to check if Hasura is running
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        # Readiness probe to check if Hasura is ready to accept connections
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3 