apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resources that should be applied together
resources:
  - graphql-deployment.yaml
  - graphql-service.yaml
  - graphql-migrations-job.yaml

# Common labels to apply to all resources
labels:
  app.kubernetes.io/name: graphql
  app.kubernetes.io/part-of: posey
  app.kubernetes.io/managed-by: kustomize
  tier: auth
  service-type: auth 