image:
  repository: poseylabs/posey-auth
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "posey-auth"

serviceAccount:
  create: true
  automount: true
  name: "posey-auth"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9999 # Align with the application's AUTH_PORT
  ingressPortName: http # Explicitly setting ingress port name

ingress:
  subdomain: auth.api

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: false # Auth service likely doesn't need persistent storage

configOverrides:
  logLevel: INFO
  telemetryDisabled: true

envFromSecret:
  enabled: true
  secretName: posey-prod-services-env-vars