image:
  repository: poseylabs/posey-auth
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "posey-auth"

serviceAccount:
  create: true
  automount: true
  name: "posey-auth"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000 # Assuming port 3000 for auth service
  ingressPortName: http # Explicitly setting ingress port name

ingress:
  subdomain: auth # Exposing via auth subdomain

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: false # Auth service likely doesn't need persistent storage

configOverrides:
  logLevel: INFO
  telemetryDisabled: true

envFromSecret:
  enabled: false
  secretName: posey-prod-data-env-vars

global:
  partOf: posey
  image:
    registry: docker.io
    pullPolicy: Always
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  replicaCount: 1 