apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-couchbase-secrets
  labels:
    app: {{ .Release.Name }}-couchbase
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  couchbase-password: {{ .Values.databases.couchbase.password | b64enc | quote }} 