apiVersion: apps/v1
kind: Deployment
metadata:
  name: posey-voyager
  namespace: posey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posey-voyager
  template:
    metadata:
      labels:
        app: posey-voyager
    spec:
      containers:
      - name: posey-voyager
        image: posey-voyager:latest  # You'll need to build and push this image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7777
        resources:
          limits:
            memory: 4Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: "0.5"
        envFrom:
        - configMapRef:
            name: posey-shared-env
        - secretRef:
            name: posey-secrets
        volumeMounts:
        - name: voyager-data
          mountPath: /src/data
        - name: voyager-cache
          mountPath: /src/cache
      volumes:
      - name: voyager-data
        persistentVolumeClaim:
          claimName: voyager-data-pvc
      - name: voyager-cache
        persistentVolumeClaim:
          claimName: voyager-cache-pvc 