apiVersion: v1
kind: Service
metadata:
  name: posey-voyager
  namespace: posey
  labels:
    app: posey-voyager
spec:
  selector:
    app: posey-voyager
  ports:
  - port: 7777
    targetPort: 7777
    nodePort: 30777
  type: NodePort 