apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voyager-data-pvc
  namespace: posey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voyager-cache-pvc
  namespace: posey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 