apiVersion: v1
kind: Service
metadata:
  name: posey-agents
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: posey-agents
    tier: backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.services.agents.port }}
    targetPort: {{ .Values.services.agents.containerPort | default 8080 }}
    protocol: TCP
    name: http
  selector:
    app: posey-agents 