# /k8s/charts/base-values.yaml
# Shared default values for Posey Helm charts

# Default replica count
replicaCount: 1

image:
  # registry: is now handled globally via helm parameters in ApplicationSet
  # repository: must be set by the specific chart
  pullPolicy: Always
  tag: "" # Defaults to Chart.appVersion

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000

# Default service configuration (can be overridden)
service:
  type: ClusterIP
  # port: must be set by the specific chart

# Default persistence config (can be overridden)
persistence:
  enabled: true
  storageClassName: "standard-rwx" # Needs verification per cluster/env
  accessModes: [ "ReadWriteOnce" ]
  size: 10Gi

# Default resource requests/limits are NOT set here.
# They are injected globally via ApplicationSet helm parameters (`global.resources.*`)
# to allow easier overriding without complex value merging.
# resources: {}

nodeSelector: {}
tolerations: []
affinity: {} 