global:
  partOf: posey
  serviceAccount:
    create: false
  image:
    registry: docker.io/poseylabs
    pullPolicy: Always
  resources:
    limits:
      cpu: "250m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "64Mi"

replicaCount: 1

image:
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}

service:
  type: ClusterIP

persistence:
  enabled: true
  storageClassName: "standard-rwo"
  accessModes: [ "ReadWriteOnce" ]
  size: 10Gi

nodeSelector: {}
tolerations: []
affinity: {} 