global:
  partOf: posey
  serviceAccount:
    create: false
  image:
    registry: docker.io/poseylabs
    pullPolicy: Always
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "128Mi"

replicaCount: 1

image:
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

service:
  type: ClusterIP
  port: 3333

persistence:
  enabled: true
  storageClassName: "standard-rwx"
  accessModes: [ "ReadWriteOnce" ]
  size: 10Gi

nodeSelector: {}
tolerations: []
affinity: {} 