apiVersion: apps/v1
kind: Deployment # Using Deployment instead of StatefulSet as persistence is disabled
metadata:
  name: {{ include "posey-auth.fullname" . }}
  labels:
    {{- include "posey-auth.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      {{- include "posey-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "posey-auth.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "posey-auth.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.ingressPortName | default "http" }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: {{ .Values.configOverrides.logLevel | quote }}
            - name: TELEMETRY_DISABLED
              value: {{ .Values.configOverrides.telemetryDisabled | quote }}
          {{- if .Values.envFromSecret.enabled }}
          envFrom:
            - secretRef:
                name: posey-prod-core-env-vars
            - secretRef:
                name: {{ .Values.envFromSecret.secretName }}
          {{- end }}
          resources:
            {{- toYaml .Values.global.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 