apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    app: {{ .Release.Name }}-qdrant
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.qdrant.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 6334
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Release.Name }}-qdrant 