apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    app: {{ .Release.Name }}-qdrant
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-qdrant
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-qdrant
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.services.qdrant.port }}
              name: http
            - containerPort: 6334
              name: grpc
          env:
            - name: QDRANT__SERVICE__HTTP_PORT
              value: {{ .Values.services.qdrant.port | quote }}
            - name: QDRANT__SERVICE__GRPC_PORT
              value: "6334"
            - name: QDRANT__STORAGE__OPTIMIZERS__DEFAULT_SEGMENT_NUMBER
              value: "2"
            - name: QDRANT__STORAGE__OPTIMIZERS__INDEXING_THRESHOLD
              value: "20000"
            - name: QDRANT__STORAGE__OPTIMIZERS__MEMMAP_THRESHOLD
              value: "10000"
            - name: QDRANT__STORAGE__OPTIMIZERS__VACUUM_MIN_VECTOR_NUMBER
              value: "1000"
            - name: QDRANT__STORAGE__OPTIMIZERS__DEFAULT_FLUSH_INTERVAL_SEC
              value: "5"
            - name: QDRANT__STORAGE__OPTIMIZERS__FORCE_MERGE_MAX_SEGMENTS_PER_SHARD
              value: "3"
            - name: QDRANT__STORAGE__PERFORMANCE__MAX_SEARCH_THREADS
              value: "1"
            - name: QDRANT__CLUSTER__ENABLED
              value: "false"
          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: qdrant-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi 