name: Build and Push Service Images

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'services/**'
      - '.github/workflows/build-push-images.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (default: latest)'
        required: false
        default: 'latest'

jobs:
  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login
      
      - name: Set image tag
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "TAG=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          fi
      
      - name: Build and push images
        run: |
          chmod +x ./scripts/docker-build-push.sh
          ./scripts/docker-build-push.sh ${{ env.TAG }}
      
      - name: Notify success
        if: success()
        run: |
          echo "✅ Successfully built and pushed all service images with tag: ${{ env.TAG }}"
      
      - name: Notify failure
        if: failure()
        run: |
          echo "❌ Failed to build and push service images. Check the logs for details." 