name: Build Vector DB Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'data/vector.db/**'
      - '.github/workflows/data-vector-db.yml'

env:
  DOCTL_VERSION: 1.92.1
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'PRODUCTION' || 'STAGING' }}
  SERVICE: vector.db
  DOCKER_IMAGE_NAME: posey-vector-db
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  # Enable debug logging for npm and GitHub Actions
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true
  NPM_CONFIG_LOGLEVEL: verbose

jobs:
  build-vector-db:
    # Skip this job if it was triggered by the orchestrator
    if: github.event_name != 'workflow_dispatch' || !contains(github.actor, 'github-actions[bot]')
    name: Vector DB Job
    runs-on:
      group: posey-runners
    environment: PRODUCTION
    timeout-minutes: 90  # Increased from 60 to 120 minutes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Reconfigure git to use HTTP instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - name: Configure network
        run: |
          echo "Setting DNS cache TTL to improve networking..."
          echo "options single-request-reopen" | sudo tee -a /etc/resolv.conf
          echo "options timeout:10" | sudo tee -a /etc/resolv.conf
          echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
          echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf
          # Increase TCP performance
          sudo sysctl -w net.ipv4.tcp_slow_start_after_idle=0
          sudo sysctl -w net.ipv4.tcp_fastopen=3
          
      - name: Install doctl
        run: |
          cd /tmp
          curl -sL --retry 5 --retry-delay 5 https://github.com/digitalocean/doctl/releases/download/v${{ env.DOCTL_VERSION }}/doctl-${{ env.DOCTL_VERSION }}-linux-arm64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin/
          doctl version
          doctl auth init -t ${{ secrets.DO_API_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        timeout-minutes: 2
        run: |
          doctl registry login --expiry-seconds 7200
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.0
          buildkitd-flags: --debug
          driver: docker-container
          
      - name: Setup Docker Buildx with Memory Limits
        run: |
          docker buildx create --name multiplatform-builder --driver docker-container --driver-opt image=moby/buildkit:buildx-stable-1 --use --bootstrap
          docker buildx inspect
          
      - name: Pull existing images for caching
        run: |
          echo "Pulling existing images for caching..."
          # Pull latest, buildcache, and env-specific images to use as cache
          docker pull registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:latest || echo "No latest image found"
          docker pull registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:buildcache || echo "No buildcache image found"
          docker pull registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:${ENVIRONMENT} || echo "No ${ENVIRONMENT} image found"
          
      - name: Debug directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Content of data directory:"
          ls -la data/
          echo "Content of data/vector.db directory:"
          ls -la data/vector.db/
          
      - name: Build Vector DB
        timeout-minutes: 90
        run: |
          # Create yarn logs directory
          mkdir -p yarn-logs
          
          echo "Building data service $SERVICE as $DOCKER_IMAGE_NAME..."
          
          # Add retries for build
          for i in {1..3}; do
            echo "Attempt $i of 3..."
            
            if set -o pipefail && DOCKER_BUILDKIT=1 docker buildx build \
              --platform linux/amd64 \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              --build-arg NODE_ENV=production \
              --build-arg BUILDKIT_MAX_PARALLELISM=4 \
              --build-arg YARN_ENABLE_TELEMETRY=false \
              --build-arg YARN_ENABLE_PROGRESS_BARS=true \
              --build-arg YARN_VERBOSE=true \
              --build-arg DEBUG="yarn*,pnp*" \
              --build-arg YARN_LOG_LEVEL=info \
              --build-arg YARN_NETWORK_TIMEOUT=600000 \
              --memory=12g \
              --progress=plain \
              --cache-from type=registry,ref=registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:buildcache \
              --cache-from registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:latest \
              --cache-from registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:${{ env.ENVIRONMENT }} \
              --cache-to type=registry,ref=registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:buildcache,mode=max \
              -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:latest \
              -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:${{ env.ENVIRONMENT }} \
              -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:$(echo $GITHUB_SHA | cut -c1-7) \
              -f data/vector.db/Dockerfile \
              --push \
              . 2>&1 | tee yarn-logs/build.log; then
              echo "Build successful!"
              exit 0
            else
              echo "Build failed with exit code $?"
              if [ $i -eq 3 ]; then
                echo "All retry attempts failed"
                exit 1
              fi
              sleep 15
            fi
          done

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yarn-logs-${{ github.sha }}
          path: yarn-logs
          retention-days: 5
          compression-level: 6
          
      - name: Verify image availability
        run: |
          echo "Verifying image availability in registry..."
          for i in {1..5}; do
            doctl registry repository list-tags ${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME} --format Tag && break || sleep 10
          done
          exit 0  # Ensure step doesn't fail if repository doesn't exist yet 