name: Build Postgres Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'data/postgres/**'
      - '.github/workflows/data-postgres.yml'

env:
  DOCTL_VERSION: 1.92.1
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'PRODUCTION' || 'STAGING' }}
  SERVICE: postgres
  DOCKER_IMAGE_NAME: postgres

jobs:
  build-postgres:
    name: Build Postgres Service
    runs-on:
      group: posey-runners
    environment: PRODUCTION
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install doctl
        run: |
          cd /tmp
          curl -sL https://github.com/digitalocean/doctl/releases/download/v${{ env.DOCTL_VERSION }}/doctl-${{ env.DOCTL_VERSION }}-linux-arm64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin/
          doctl version
          doctl auth init -t ${{ secrets.DO_API_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: |
          doctl registry login --expiry-seconds 3600
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.0
          
      - name: Docker Buildx Configuration
        run: |
          docker buildx create --name multiplatform-builder --driver docker-container --use
          docker buildx inspect --bootstrap
          
      - name: Debug directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Content of data directory:"
          ls -la data/
          echo "Content of data/postgres directory:"
          ls -la data/postgres/
          echo "Looking for src directory:"
          find data/postgres -type d -name "src" || echo "src directory not found"
          echo "Checking Dockerfile existence:"
          if [ -f "data/${SERVICE}/Dockerfile" ]; then
            echo "Dockerfile exists at data/${SERVICE}/Dockerfile"
            cat data/${SERVICE}/Dockerfile | grep -n COPY
          else
            echo "ERROR: Dockerfile not found at data/${SERVICE}/Dockerfile"
          fi
          
      - name: Build Postgres
        timeout-minutes: 15
        run: |
          # Build using the data/postgres directory as context
          cd data/${SERVICE}
          
          echo "Building data service $SERVICE as $DOCKER_IMAGE_NAME..."
          
          # Build with Docker Buildx
          DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain docker buildx build \
            --platform linux/amd64 \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:latest \
            --cache-from registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:${{ env.ENVIRONMENT }} \
            -t ${DOCKER_IMAGE_NAME} \
            -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:latest \
            -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:${{ env.ENVIRONMENT }} \
            -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME}:$(echo $GITHUB_SHA | cut -c1-7) \
            -f Dockerfile \
            --push \
            . 