name: Posey Deploy Manager

on:
  workflow_run:
    workflows:
      - "Build Voyager Service"
      - "Build Auth Service"
      - "Build Supertokens Service"
      - "Build MCP Service"
      - "Build Agents Service"
      - "Build Cron Service"
      - "Build Postgres Service"
      - "Build Vector DB Service"
      - "Build Couchbase Service"
    types:
      - completed
    branches:
      - main  # Only deploy from main branch
  workflow_dispatch:  # Keep manual trigger

env:
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'PRODUCTION' || 'STAGING' }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Deploy to Kubernetes
    runs-on:
      group: posey-runners
    environment: PRODUCTION
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
          # Setup kubeconfig for DO Kubernetes
          doctl kubernetes cluster kubeconfig save ${{ secrets.DO_KUBERNETES_CLUSTER_ID }}
      
      - name: Generate service secrets and deploy
        run: |
          cd services
          # Create temporary .env file for services
          cat > .env << EOF
          # Core Application Settings
          NODE_ENV=production
          ENVIRONMENT=${{ env.ENVIRONMENT }}
          
          # Service Ports & URLs
          AUTH_PORT=${{ secrets.AUTH_PORT || '9999' }}
          MCP_PORT=${{ secrets.MCP_PORT || '5050' }}
          VOYAGER_PORT=${{ secrets.VOYAGER_PORT || '7777' }}
          SUPER_TOKENS_PORT=${{ secrets.SUPER_TOKENS_PORT || '3567' }}
          
          # Auth Service
          AUTH_API_DOMAIN=${{ secrets.AUTH_API_DOMAIN || 'http://posey-auth' }}
          AUTH_BASE_URL=${{ secrets.AUTH_BASE_URL || 'http://posey-auth' }}
          UI_BASE_URL=${{ secrets.UI_BASE_URL || 'https://posey.ai' }}
          COOKIE_DOMAIN=${{ secrets.COOKIE_DOMAIN || '.posey.ai' }}
          
          # And the rest of your environment variables...
          EOF
          
          # Generate sealed secrets
          cd ..
          export GITHUB_ACTIONS=true
          ./scripts/sealed-secrets/create-services-secrets.sh
          
          # Deploy using ArgoCD or kubectl
          # (rest of your deployment script)