name: Deploy Core Services

on:
  workflow_call: # This workflow is meant to be called by other workflows

jobs:
  deploy-core-services:
    name: Deploy Core Services
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Kubernetes config
        run: doctl kubernetes cluster kubeconfig save posey-cluster

      #----------------------------------------------
      # Deploy Agents Service
      #----------------------------------------------
      - name: Deploy Agents Service
        run: |
          kubectl apply -k k8s/agents/
          
          # Wait for Agents to be ready
          echo "Waiting for Agents service to be ready..."
          kubectl wait --for=condition=ready pod -l app=posey-agents --timeout=300s

      #----------------------------------------------
      # Deploy MCP Service
      #----------------------------------------------
      - name: Deploy MCP Service
        run: |
          kubectl apply -k k8s/mcp/
          
          # Wait for MCP to be ready
          echo "Waiting for MCP service to be ready..."
          kubectl wait --for=condition=ready pod -l app=posey-mcp --timeout=300s
          
      #----------------------------------------------
      # Verify Core Services
      #----------------------------------------------  
      - name: Verify Core Services
        run: |
          echo "Core services deployed:"
          kubectl get pods -l tier=core
          
          # Test Agents service health endpoint
          AGENTS_POD=$(kubectl get pods -l app=posey-agents -o jsonpath="{.items[0].metadata.name}")
          if [ -n "$AGENTS_POD" ]; then
            echo "Testing Agents service health endpoint..."
            kubectl exec $AGENTS_POD -- curl -s localhost:5555/health || echo "Agents service health check failed"
          fi
          
          # Test MCP service health endpoint
          MCP_POD=$(kubectl get pods -l app=posey-mcp -o jsonpath="{.items[0].metadata.name}")
          if [ -n "$MCP_POD" ]; then
            echo "Testing MCP service health endpoint..."
            kubectl exec $MCP_POD -- curl -s localhost:5050/health || echo "MCP service health check failed"
          fi 