name: Posey Build Orchestrator

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'services/*/Dockerfile'
      - 'data/*/Dockerfile'
      - '.github/workflows/service-*.yml'
      - '.github/workflows/data-*.yml'

# Add permissions to allow workflow dispatch
permissions:
  contents: read
  actions: write

env:
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'PRODUCTION' || 'STAGING' }}

jobs:
  list-workflows:
    name: List Available Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: List available workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Available workflows:"
          gh workflow list

  trigger-service-builds:
    name: Trigger Service Builds
    needs: list-workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Trigger Individual Service Workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Function to trigger workflow
          trigger_workflow() {
            PREFIX=$1
            SERVICE=$2
            
            echo "Triggering workflow for $SERVICE service"
            
            # Try to trigger the workflow with exact filename
            gh workflow run "${PREFIX}-${SERVICE}.yml" --ref "${{ github.ref_name }}" || {
              echo "Failed to trigger workflow for $SERVICE"
              return 1
            }
            
            echo "Successfully triggered workflow for $SERVICE"
          }
          
          # Trigger service workflows with error handling
          SERVICES="voyager auth supertokens mcp agents cron"
          for SERVICE in $SERVICES; do
            trigger_workflow "service" "$SERVICE" || echo "Failed to trigger $SERVICE workflow, continuing..."
          done
          
          # Trigger data services workflows with error handling
          DATA_SERVICES="postgres vector-db couchbase"
          for SERVICE in $DATA_SERVICES; do
            trigger_workflow "data" "$SERVICE" || echo "Failed to trigger $SERVICE workflow, continuing..."
          done
