name: Build Auth Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'services/auth/**'
      - '.github/workflows/service-auth.yml'

env:
  DOCTL_VERSION: 1.92.1
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'PRODUCTION' || 'STAGING' }}
  SERVICE: auth
  DOCKER_IMAGE_NAME: posey-auth
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  # Enable debug logging for npm and GitHub Actions
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true
  NPM_CONFIG_LOGLEVEL: verbose

jobs:
  build-auth:
    name: Build Auth Service
    runs-on:
      group: posey-runners
    environment: PRODUCTION
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Enable npm debug logs
        run: |
          npm config set loglevel verbose
          npm config set timing true
          npm config set logs-max 10
          npm config set logs-dir ./npm-logs
          mkdir -p ./npm-logs

      - name: Reconfigure git to use HTTP instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Configure network
        run: |
          echo "Setting DNS cache TTL to improve networking..."
          echo "options single-request-reopen" | sudo tee -a /etc/resolv.conf
          echo "options timeout:10" | sudo tee -a /etc/resolv.conf
          # Increase TCP performance
          sudo sysctl -w net.ipv4.tcp_slow_start_after_idle=0
          sudo sysctl -w net.ipv4.tcp_fastopen=3

      - name: Install doctl
        run: |
          cd /tmp
          curl -sL --retry 5 --retry-delay 5 https://github.com/digitalocean/doctl/releases/download/v${{ env.DOCTL_VERSION }}/doctl-${{ env.DOCTL_VERSION }}-linux-arm64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin/
          doctl version
          doctl auth init -t ${{ secrets.DO_API_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: |
          doctl registry login --expiry-seconds 7200
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.0
          
      - name: Docker Buildx Configuration
        run: |
          docker buildx create --name multiplatform-builder --driver docker-container --use --bootstrap
          docker buildx inspect
          
      - name: Build Auth Service
        timeout-minutes: 90
        run: |
          echo "Building ${SERVICE}..."
          
          docker buildx build \
            --platform linux/amd64 \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg NODE_ENV=production \
            --build-arg NPM_CONFIG_REGISTRY=https://registry.npmjs.org/ \
            --build-arg NPM_CONFIG_FETCH_RETRIES=5 \
            --build-arg NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=20000 \
            --build-arg NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=120000 \
            --build-arg NPM_CONFIG_LOGLEVEL=verbose \
            --build-arg NPM_CONFIG_TIMING=true \
            --build-arg NPM_CONFIG_LOGS_MAX=10 \
            --build-arg NPM_CONFIG_LOGS_DIR=/app/services/auth/npm-logs \
            --cache-from registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME:-$SERVICE}:latest \
            --cache-from registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME:-$SERVICE}:${{ env.ENVIRONMENT }} \
            -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME:-$SERVICE}:latest \
            -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME:-$SERVICE}:${{ env.ENVIRONMENT }} \
            -t registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${DOCKER_IMAGE_NAME:-$SERVICE}:$(echo $GITHUB_SHA | cut -c1-7) \
            -f services/${SERVICE}/Dockerfile \
            --push \
            .

      - name: Upload npm logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs-${{ github.sha }}
          path: |
            ./npm-logs
            /app/services/auth/npm-logs
          retention-days: 5
          compression-level: 6  # Balanced between speed and size
          
      - name: Push images to registry
        run: |
          echo "Pushing ${SERVICE} images to registry..."
          docker push registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${SERVICE}:latest || true
          docker push registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${SERVICE}:${{ env.ENVIRONMENT }} || true
          docker push registry.digitalocean.com/${{ secrets.DO_REGISTRY_NAME }}/${SERVICE}:$(echo $GITHUB_SHA | cut -c1-7) || true
          
      - name: Verify push status
        run: |
          echo "Verifying image availability in registry..."
          doctl registry repository list-tags ${{ secrets.DO_REGISTRY_NAME }}/${SERVICE} --format Tag 